services:
  invoice-extractor:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app/app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    ports:
      - "8000:8000"
